export interface PracticeArea {
  slug: string
  title: string
  shortTitle: string
  description: string
  heroImage: string
  category: string
  injuries?: string[]
}

export const practiceAreas: PracticeArea[] = [
  // General
  { slug: 'personal-injury-lawyer', title: 'Personal Injury Lawyer', shortTitle: 'Personal Injury', description: 'Comprehensive personal injury legal services for all types of accidents and injuries.', heroImage: 'personal-injury.jpg', category: 'General', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Whiplash & Neck Injuries', 'Back Injuries', 'Internal Organ Damage', 'Burns & Scarring', 'Soft Tissue Injuries'] },

  // Vehicle Accidents
  { slug: 'car-accident-lawyer', title: 'Car Accident Lawyer', shortTitle: 'Car Accidents', description: 'Experienced car accident lawyers fighting for maximum compensation.', heroImage: 'car-accident.jpg', category: 'Vehicle Accidents', injuries: ['Whiplash & Neck Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Internal Bleeding', 'Soft Tissue Injuries', 'Back Injuries', 'Concussions'] },
  { slug: 'truck-accident-lawyer', title: 'Truck Accident Lawyer', shortTitle: 'Truck Accidents', description: 'Truck accident attorneys with experience against major carriers.', heroImage: 'truck-accident.jpg', category: 'Vehicle Accidents', injuries: ['Catastrophic Crush Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries & Paralysis', 'Severe Burns', 'Multiple Fractures', 'Amputation Injuries', 'Internal Organ Damage', 'Wrongful Death'] },
  { slug: '18-wheeler-accident-lawyer', title: '18-Wheeler Accident Lawyer', shortTitle: '18-Wheeler Accidents', description: 'Specialized 18-wheeler and semi-truck accident representation.', heroImage: '18-wheeler.jpg', category: 'Vehicle Accidents', injuries: ['Catastrophic Crush Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries & Paralysis', 'Severe Burns', 'Multiple Fractures', 'Amputation Injuries', 'Internal Organ Damage', 'Wrongful Death'] },
  { slug: 'motorcycle-accident-lawyer', title: 'Motorcycle Accident Lawyer', shortTitle: 'Motorcycle Accidents', description: 'Motorcycle accident lawyers who understand rider rights.', heroImage: 'motorcycle.jpg', category: 'Vehicle Accidents', injuries: ['Road Rash & Skin Abrasions', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Leg & Knee Injuries', 'Arm & Shoulder Injuries', 'Internal Organ Damage', 'Facial Injuries & Scarring'] },
  { slug: 'hit-and-run-lawyer', title: 'Hit and Run Lawyer', shortTitle: 'Hit and Run', description: 'Pursuing justice for hit and run accident victims.', heroImage: 'hit-and-run.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Soft Tissue Injuries', 'Internal Bleeding', 'Psychological Trauma', 'Whiplash & Neck Injuries', 'Road Rash'] },
  { slug: 'drunk-driving-accident-lawyer', title: 'Drunk Driving Accident Lawyer', shortTitle: 'Drunk Driving Accidents', description: 'Holding drunk drivers accountable for their actions.', heroImage: 'drunk-driving.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries & Paralysis', 'Broken Bones & Fractures', 'Internal Organ Damage', 'Severe Burns', 'Wrongful Death', 'Disfigurement & Scarring', 'Permanent Disability'] },
  { slug: 'rideshare-accident-lawyer', title: 'Rideshare Accident Lawyer', shortTitle: 'Rideshare Accidents', description: 'Uber and Lyft accident claims handled expertly.', heroImage: 'rideshare.jpg', category: 'Vehicle Accidents', injuries: ['Whiplash & Neck Injuries', 'Back Injuries', 'Traumatic Brain Injuries (TBI)', 'Broken Bones', 'Soft Tissue Injuries', 'Concussions', 'Internal Injuries', 'Psychological Trauma'] },
  { slug: 'uber-lyft-accident-lawyer', title: 'Uber/Lyft Accident Lawyer', shortTitle: 'Uber/Lyft Accidents', description: 'Navigating complex rideshare accident claims.', heroImage: 'uber-lyft.jpg', category: 'Vehicle Accidents', injuries: ['Whiplash & Neck Injuries', 'Back Injuries', 'Traumatic Brain Injuries (TBI)', 'Broken Bones', 'Soft Tissue Injuries', 'Concussions', 'Internal Injuries', 'Psychological Trauma'] },
  { slug: 'box-truck-accident-lawyer', title: 'Box Truck Accident Lawyer', shortTitle: 'Box Truck Accidents', description: 'Box truck and delivery vehicle accident claims.', heroImage: 'box-truck.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Crush Injuries', 'Internal Bleeding', 'Whiplash & Neck Injuries', 'Back Injuries', 'Soft Tissue Injuries'] },
  { slug: 'delivery-truck-accident-lawyer', title: 'Delivery Truck Accident Lawyer', shortTitle: 'Delivery Truck Accidents', description: 'Delivery vehicle accident representation.', heroImage: 'delivery-truck.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Crush Injuries', 'Internal Bleeding', 'Whiplash & Neck Injuries', 'Back Injuries', 'Soft Tissue Injuries'] },
  { slug: 'dump-truck-accident-lawyer', title: 'Dump Truck Accident Lawyer', shortTitle: 'Dump Truck Accidents', description: 'Dump truck accident injury claims.', heroImage: 'dump-truck.jpg', category: 'Vehicle Accidents', injuries: ['Catastrophic Crush Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Amputation Injuries', 'Multiple Fractures', 'Internal Organ Damage', 'Severe Burns', 'Wrongful Death'] },
  { slug: 'garbage-truck-accident-lawyer', title: 'Garbage Truck Accident Lawyer', shortTitle: 'Garbage Truck Accidents', description: 'Garbage and waste truck accident claims.', heroImage: 'garbage-truck.jpg', category: 'Vehicle Accidents', injuries: ['Crush Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Internal Organ Damage', 'Amputation Injuries', 'Back Injuries', 'Soft Tissue Injuries'] },
  { slug: 'tanker-truck-accident-lawyer', title: 'Tanker Truck Accident Lawyer', shortTitle: 'Tanker Truck Accidents', description: 'Tanker truck and hazmat accident claims.', heroImage: 'tanker-truck.jpg', category: 'Vehicle Accidents', injuries: ['Severe Chemical Burns', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Toxic Exposure Injuries', 'Respiratory Damage', 'Catastrophic Burns', 'Amputation Injuries', 'Wrongful Death'] },
  { slug: 'tow-truck-accident-lawyer', title: 'Tow Truck Accident Lawyer', shortTitle: 'Tow Truck Accidents', description: 'Tow truck accident injury claims.', heroImage: 'tow-truck.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Crush Injuries', 'Internal Bleeding', 'Whiplash & Neck Injuries', 'Back Injuries', 'Soft Tissue Injuries'] },
  { slug: 'concrete-mixer-accident-lawyer', title: 'Concrete Mixer Accident Lawyer', shortTitle: 'Concrete Mixer Accidents', description: 'Concrete mixer truck accident representation.', heroImage: 'concrete-mixer.jpg', category: 'Vehicle Accidents', injuries: ['Catastrophic Crush Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Multiple Fractures', 'Internal Organ Damage', 'Chemical Burns', 'Amputation Injuries', 'Wrongful Death'] },
  { slug: 'oversized-load-accident-lawyer', title: 'Oversized Load Accident Lawyer', shortTitle: 'Oversized Load Accidents', description: 'Wide load and oversized cargo accident claims.', heroImage: 'oversized-load.jpg', category: 'Vehicle Accidents', injuries: ['Crush Injuries', 'Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Multiple Fractures', 'Internal Organ Damage', 'Impalement Injuries', 'Amputation Injuries', 'Wrongful Death'] },
  { slug: 'head-on-collision-lawyer', title: 'Head-On Collision Lawyer', shortTitle: 'Head-On Collisions', description: 'Serious head-on collision injury claims.', heroImage: 'head-on.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries & Paralysis', 'Chest & Rib Injuries', 'Facial Fractures', 'Internal Organ Damage', 'Broken Bones & Fractures', 'Wrongful Death', 'Severe Burns'] },
  { slug: 'rear-end-collision-lawyer', title: 'Rear-End Collision Lawyer', shortTitle: 'Rear-End Collisions', description: 'Rear-end accident injury representation.', heroImage: 'rear-end.jpg', category: 'Vehicle Accidents', injuries: ['Whiplash & Neck Injuries', 'Back Injuries', 'Herniated Discs', 'Concussions', 'Soft Tissue Injuries', 'Spinal Cord Injuries', 'Traumatic Brain Injuries (TBI)', 'Shoulder Injuries'] },
  { slug: 't-bone-accident-lawyer', title: 'T-Bone Accident Lawyer', shortTitle: 'T-Bone Accidents', description: 'Side-impact and T-bone collision claims.', heroImage: 't-bone.jpg', category: 'Vehicle Accidents', injuries: ['Rib & Chest Injuries', 'Hip & Pelvis Fractures', 'Spinal Cord Injuries', 'Traumatic Brain Injuries (TBI)', 'Internal Organ Damage', 'Arm & Shoulder Injuries', 'Broken Bones', 'Wrongful Death'] },
  { slug: 'multi-vehicle-accident-lawyer', title: 'Multi-Vehicle Accident Lawyer', shortTitle: 'Multi-Vehicle Accidents', description: 'Complex multi-car pileup claims.', heroImage: 'multi-vehicle.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Spinal Cord Injuries', 'Multiple Fractures', 'Internal Bleeding', 'Crush Injuries', 'Severe Burns', 'Wrongful Death', 'Permanent Disability'] },
  { slug: 'distracted-driving-lawyer', title: 'Distracted Driving Lawyer', shortTitle: 'Distracted Driving', description: 'Texting and distracted driver accident claims.', heroImage: 'distracted-driving.jpg', category: 'Vehicle Accidents', injuries: ['Traumatic Brain Injuries (TBI)', 'Whiplash & Neck Injuries', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Internal Injuries', 'Soft Tissue Injuries', 'Back Injuries', 'Psychological Trauma'] },
  { slug: 'uninsured-motorist-lawyer', title: 'Uninsured Motorist Lawyer', shortTitle: 'Uninsured Motorist', description: 'UM/UIM claims against uninsured drivers.', heroImage: 'uninsured-motorist.jpg', category: 'Vehicle Accidents', injuries: ['Whiplash & Neck Injuries', 'Traumatic Brain Injuries (TBI)', 'Broken Bones & Fractures', 'Back Injuries', 'Soft Tissue Injuries', 'Internal Injuries', 'Spinal Cord Injuries', 'Concussions'] },

  // Serious Injuries
  { slug: 'wrongful-death-lawyer', title: 'Wrongful Death Lawyer', shortTitle: 'Wrongful Death', description: 'Compassionate wrongful death representation for families.', heroImage: 'wrongful-death.jpg', category: 'Serious Injuries', injuries: ['Fatal Traumatic Brain Injuries', 'Fatal Internal Bleeding', 'Fatal Spinal Cord Injuries', 'Fatal Burns', 'Fatal Crushing Injuries', 'Fatal Medical Malpractice', 'Fatal Workplace Accidents', 'Fatal Vehicle Accidents'] },
  { slug: 'brain-injury-lawyer', title: 'Brain Injury Lawyer', shortTitle: 'Brain Injuries', description: 'Brain injury and head trauma legal representation.', heroImage: 'brain-injury.jpg', category: 'Serious Injuries', injuries: ['Traumatic Brain Injuries (TBI)', 'Concussions', 'Skull Fractures', 'Brain Contusions', 'Diffuse Axonal Injuries', 'Coup-Contrecoup Injuries', 'Penetrating Brain Injuries', 'Anoxic Brain Injuries'] },
  { slug: 'traumatic-brain-injury-lawyer', title: 'Traumatic Brain Injury Lawyer', shortTitle: 'Traumatic Brain Injuries', description: 'TBI and head injury legal representation.', heroImage: 'brain-injury.jpg', category: 'Serious Injuries', injuries: ['Severe TBI', 'Moderate TBI', 'Mild TBI (Concussions)', 'Skull Fractures', 'Brain Hemorrhages', 'Brain Contusions', 'Diffuse Axonal Injuries', 'Cognitive Impairments'] },
  { slug: 'spinal-cord-injury-lawyer', title: 'Spinal Cord Injury Lawyer', shortTitle: 'Spinal Cord Injuries', description: 'Spinal cord and paralysis injury claims.', heroImage: 'spinal-cord.jpg', category: 'Serious Injuries', injuries: ['Complete Paralysis', 'Incomplete Paralysis', 'Paraplegia', 'Quadriplegia', 'Herniated Discs', 'Vertebral Fractures', 'Spinal Stenosis', 'Nerve Damage'] },
  { slug: 'burn-injury-lawyer', title: 'Burn Injury Lawyer', shortTitle: 'Burn Injuries', description: 'Serious burn injury compensation claims.', heroImage: 'burn-injury.jpg', category: 'Serious Injuries', injuries: ['First-Degree Burns', 'Second-Degree Burns', 'Third-Degree Burns', 'Fourth-Degree Burns', 'Chemical Burns', 'Electrical Burns', 'Inhalation Injuries', 'Permanent Scarring'] },
  { slug: 'amputation-injury-lawyer', title: 'Amputation Injury Lawyer', shortTitle: 'Amputation Injuries', description: 'Limb loss and amputation injury claims.', heroImage: 'amputation.jpg', category: 'Serious Injuries', injuries: ['Traumatic Amputations', 'Surgical Amputations', 'Arm & Hand Amputations', 'Leg & Foot Amputations', 'Finger & Toe Amputations', 'Partial Limb Loss', 'Phantom Limb Pain', 'Prosthetic Needs'] },
  { slug: 'paralysis-injury-lawyer', title: 'Paralysis Injury Lawyer', shortTitle: 'Paralysis Injuries', description: 'Paralysis and mobility loss claims.', heroImage: 'paralysis.jpg', category: 'Serious Injuries', injuries: ['Paraplegia', 'Quadriplegia', 'Monoplegia', 'Hemiplegia', 'Partial Paralysis', 'Temporary Paralysis', 'Facial Paralysis', 'Permanent Disability'] },
  { slug: 'coma-injury-lawyer', title: 'Coma Injury Lawyer', shortTitle: 'Coma Injuries', description: 'Coma and severe brain injury claims.', heroImage: 'coma.jpg', category: 'Serious Injuries', injuries: ['Traumatic Coma', 'Medically-Induced Coma', 'Vegetative State', 'Brain Death', 'Anoxic Brain Injuries', 'Long-Term Cognitive Damage', 'Permanent Brain Damage', 'Memory Loss'] },
  { slug: 'back-injury-lawyer', title: 'Back Injury Lawyer', shortTitle: 'Back Injuries', description: 'Back and spine injury representation.', heroImage: 'back-injury.jpg', category: 'Serious Injuries', injuries: ['Herniated Discs', 'Bulging Discs', 'Spinal Fractures', 'Lumbar Sprains', 'Sciatica', 'Degenerative Disc Disease', 'Spinal Stenosis', 'Chronic Back Pain'] },
  { slug: 'neck-injury-lawyer', title: 'Neck Injury Lawyer', shortTitle: 'Neck Injuries', description: 'Neck injury and whiplash claims.', heroImage: 'neck-injury.jpg', category: 'Serious Injuries', injuries: ['Whiplash', 'Cervical Fractures', 'Herniated Cervical Discs', 'Neck Sprains & Strains', 'Pinched Nerves', 'Cervical Stenosis', 'Chronic Neck Pain', 'Limited Range of Motion'] },
  { slug: 'whiplash-injury-lawyer', title: 'Whiplash Injury Lawyer', shortTitle: 'Whiplash Injuries', description: 'Whiplash and soft tissue claims.', heroImage: 'whiplash.jpg', category: 'Serious Injuries', injuries: ['Acute Whiplash', 'Chronic Whiplash', 'Neck Sprains & Strains', 'Cervical Disc Injuries', 'Headaches & Migraines', 'Shoulder Pain', 'TMJ Disorders', 'Cognitive Issues'] },
  { slug: 'broken-bones-lawyer', title: 'Broken Bones Lawyer', shortTitle: 'Broken Bones', description: 'Fracture and broken bone injury claims.', heroImage: 'broken-bones.jpg', category: 'Serious Injuries', injuries: ['Simple Fractures', 'Compound Fractures', 'Comminuted Fractures', 'Spiral Fractures', 'Stress Fractures', 'Compression Fractures', 'Hip Fractures', 'Skull Fractures'] },
  { slug: 'concussion-injury-lawyer', title: 'Concussion Injury Lawyer', shortTitle: 'Concussion Injuries', description: 'Concussion and mild TBI claims.', heroImage: 'concussion.jpg', category: 'Serious Injuries', injuries: ['Mild Concussions', 'Severe Concussions', 'Post-Concussion Syndrome', 'Memory Problems', 'Cognitive Impairment', 'Headaches & Migraines', 'Dizziness & Balance Issues', 'Sleep Disorders'] },
  { slug: 'internal-injuries-lawyer', title: 'Internal Injuries Lawyer', shortTitle: 'Internal Injuries', description: 'Internal bleeding and organ damage claims.', heroImage: 'internal-injuries.jpg', category: 'Serious Injuries', injuries: ['Internal Bleeding', 'Organ Lacerations', 'Ruptured Spleen', 'Liver Damage', 'Kidney Damage', 'Lung Punctures', 'Intestinal Injuries', 'Abdominal Trauma'] },
  { slug: 'nerve-damage-lawyer', title: 'Nerve Damage Lawyer', shortTitle: 'Nerve Damage', description: 'Nerve damage and neuropathy claims.', heroImage: 'nerve-damage.jpg', category: 'Serious Injuries', injuries: ['Peripheral Nerve Damage', 'Brachial Plexus Injuries', 'Sciatica', 'Carpal Tunnel Syndrome', 'Pinched Nerves', 'Neuropathy', 'Radiculopathy', 'Chronic Pain Syndromes'] },
  { slug: 'soft-tissue-injury-lawyer', title: 'Soft Tissue Injury Lawyer', shortTitle: 'Soft Tissue Injuries', description: 'Muscle, tendon, and ligament injury claims.', heroImage: 'soft-tissue.jpg', category: 'Serious Injuries', injuries: ['Muscle Strains', 'Ligament Sprains', 'Tendon Tears', 'Contusions', 'Rotator Cuff Injuries', 'ACL & MCL Tears', 'Meniscus Tears', 'Chronic Soft Tissue Pain'] },
  { slug: 'joint-injury-lawyer', title: 'Joint Injury Lawyer', shortTitle: 'Joint Injuries', description: 'Joint damage and mobility claims.', heroImage: 'joint-injury.jpg', category: 'Serious Injuries', injuries: ['Knee Injuries', 'Shoulder Injuries', 'Hip Injuries', 'Ankle Injuries', 'Wrist Injuries', 'Elbow Injuries', 'Joint Dislocations', 'Cartilage Damage'] },
  { slug: 'road-rash-lawyer', title: 'Road Rash Lawyer', shortTitle: 'Road Rash', description: 'Motorcycle road rash injury claims.', heroImage: 'road-rash.jpg', category: 'Serious Injuries', injuries: ['First-Degree Road Rash', 'Second-Degree Road Rash', 'Third-Degree Road Rash', 'Deep Skin Abrasions', 'Skin Grafting Needs', 'Permanent Scarring', 'Infections', 'Nerve Damage'] },
  { slug: 'scarring-disfigurement-lawyer', title: 'Scarring & Disfigurement Lawyer', shortTitle: 'Scarring & Disfigurement', description: 'Permanent scarring and disfigurement claims.', heroImage: 'scarring.jpg', category: 'Serious Injuries', injuries: ['Facial Scarring', 'Burn Scars', 'Surgical Scars', 'Keloid Scars', 'Hypertrophic Scars', 'Disfigurement', 'Loss of Limb', 'Permanent Visible Injuries'] },
  { slug: 'repetitive-stress-injury-lawyer', title: 'Repetitive Stress Injury Lawyer', shortTitle: 'Repetitive Stress Injuries', description: 'RSI and repetitive motion injury claims.', heroImage: 'repetitive-stress.jpg', category: 'Serious Injuries', injuries: ['Carpal Tunnel Syndrome', 'Tendinitis', 'Tennis Elbow', 'Trigger Finger', 'Bursitis', 'Rotator Cuff Injuries', 'Cubital Tunnel Syndrome', 'De Quervain Tenosynovitis'] },

  // Workplace & Premises
  { slug: 'work-injury-lawyer', title: 'Work Injury Lawyer', shortTitle: 'Work Injuries', description: 'Work injury and on-the-job accident claims.', heroImage: 'workplace.jpg', category: 'Workplace & Premises', injuries: ['Back & Spine Injuries', 'Repetitive Stress Injuries', 'Falls From Height', 'Machinery Injuries', 'Electrocution', 'Chemical Exposure', 'Burns', 'Broken Bones'] },
  { slug: 'workplace-injury-lawyer', title: 'Workplace Injury Lawyer', shortTitle: 'Workplace Injuries', description: 'Work injury and on-the-job accident claims.', heroImage: 'workplace.jpg', category: 'Workplace & Premises', injuries: ['Back & Spine Injuries', 'Repetitive Stress Injuries', 'Falls From Height', 'Machinery Injuries', 'Electrocution', 'Chemical Exposure', 'Burns', 'Broken Bones'] },
  { slug: 'construction-accident-lawyer', title: 'Construction Accident Lawyer', shortTitle: 'Construction Accidents', description: 'Construction site injury representation.', heroImage: 'construction.jpg', category: 'Workplace & Premises', injuries: ['Falls From Scaffolding', 'Struck-By Injuries', 'Electrocution', 'Caught-Between Injuries', 'Crane Accidents', 'Trench Collapses', 'Falling Objects', 'Heavy Equipment Injuries'] },
  { slug: 'oil-field-injury-lawyer', title: 'Oil Field Injury Lawyer', shortTitle: 'Oil Field Injuries', description: 'Oilfield and energy sector injury claims.', heroImage: 'oil-field.jpg', category: 'Workplace & Premises', injuries: ['Explosions & Burns', 'Toxic Chemical Exposure', 'Heavy Equipment Injuries', 'Falls From Heights', 'Struck-By Injuries', 'Electrocution', 'Respiratory Injuries', 'Drilling Rig Accidents'] },
  { slug: 'machinery-accident-lawyer', title: 'Machinery Accident Lawyer', shortTitle: 'Machinery Accidents', description: 'Industrial machinery injury claims.', heroImage: 'machinery.jpg', category: 'Workplace & Premises', injuries: ['Amputation Injuries', 'Crush Injuries', 'Entanglement Injuries', 'Burns', 'Lacerations', 'Broken Bones', 'Electrical Injuries', 'Wrongful Death'] },
  { slug: 'electrocution-injury-lawyer', title: 'Electrocution Injury Lawyer', shortTitle: 'Electrocution Injuries', description: 'Electrical shock and electrocution claims.', heroImage: 'electrocution.jpg', category: 'Workplace & Premises', injuries: ['Electrical Burns', 'Cardiac Arrest', 'Nerve Damage', 'Muscle Damage', 'Broken Bones', 'Traumatic Brain Injuries', 'Internal Organ Damage', 'Wrongful Death'] },
  { slug: 'fall-from-height-lawyer', title: 'Fall From Height Lawyer', shortTitle: 'Falls From Height', description: 'Ladder, scaffold, and height fall claims.', heroImage: 'fall-from-height.jpg', category: 'Workplace & Premises', injuries: ['Traumatic Brain Injuries', 'Spinal Cord Injuries', 'Broken Bones & Fractures', 'Internal Organ Damage', 'Hip & Pelvis Fractures', 'Wrist & Arm Fractures', 'Wrongful Death', 'Paralysis'] },
  { slug: 'workplace-burn-lawyer', title: 'Workplace Burn Lawyer', shortTitle: 'Workplace Burns', description: 'Workplace burn and chemical burn claims.', heroImage: 'workplace-burn.jpg', category: 'Workplace & Premises', injuries: ['Chemical Burns', 'Thermal Burns', 'Electrical Burns', 'Flash Burns', 'Steam Burns', 'Inhalation Injuries', 'Scarring & Disfigurement', 'Skin Grafting Needs'] },
  { slug: 'workplace-vehicle-accident-lawyer', title: 'Workplace Vehicle Accident Lawyer', shortTitle: 'Workplace Vehicle Accidents', description: 'Forklift and workplace vehicle claims.', heroImage: 'workplace-vehicle.jpg', category: 'Workplace & Premises', injuries: ['Crush Injuries', 'Pedestrian Struck Injuries', 'Forklift Tip-Over Injuries', 'Loading Dock Accidents', 'Broken Bones', 'Internal Injuries', 'Traumatic Brain Injuries', 'Spinal Cord Injuries'] },
  { slug: 'toxic-exposure-lawyer', title: 'Toxic Exposure Lawyer', shortTitle: 'Toxic Exposure', description: 'Chemical and toxic substance claims.', heroImage: 'toxic-exposure.jpg', category: 'Workplace & Premises', injuries: ['Respiratory Diseases', 'Chemical Burns', 'Cancer', 'Neurological Damage', 'Organ Damage', 'Skin Conditions', 'Reproductive Harm', 'Chronic Illness'] },
  { slug: 'slip-and-fall-lawyer', title: 'Slip and Fall Lawyer', shortTitle: 'Slip & Fall', description: 'Premises liability slip and fall claims.', heroImage: 'slip-and-fall.jpg', category: 'Workplace & Premises', injuries: ['Hip Fractures', 'Wrist Fractures', 'Back Injuries', 'Traumatic Brain Injuries', 'Spinal Cord Injuries', 'Knee Injuries', 'Shoulder Injuries', 'Soft Tissue Injuries'] },
  { slug: 'premises-liability-lawyer', title: 'Premises Liability Lawyer', shortTitle: 'Premises Liability', description: 'Property owner negligence claims.', heroImage: 'premises-liability.jpg', category: 'Workplace & Premises', injuries: ['Slip & Fall Injuries', 'Trip & Fall Injuries', 'Assault & Battery', 'Swimming Pool Accidents', 'Elevator Accidents', 'Escalator Accidents', 'Falling Objects', 'Negligent Security Injuries'] },
  { slug: 'dog-bite-lawyer', title: 'Dog Bite Lawyer', shortTitle: 'Dog Bites', description: 'Dog attack and animal bite claims.', heroImage: 'dog-bite.jpg', category: 'Workplace & Premises', injuries: ['Puncture Wounds', 'Lacerations', 'Facial Injuries', 'Nerve Damage', 'Infections', 'Scarring & Disfigurement', 'Psychological Trauma', 'Broken Bones'] },
  { slug: 'wet-floor-accident-lawyer', title: 'Wet Floor Accident Lawyer', shortTitle: 'Wet Floor Accidents', description: 'Wet floor slip and fall claims.', heroImage: 'wet-floor.jpg', category: 'Workplace & Premises', injuries: ['Hip Fractures', 'Wrist Fractures', 'Back Injuries', 'Traumatic Brain Injuries', 'Tailbone Injuries', 'Knee Injuries', 'Ankle Injuries', 'Soft Tissue Injuries'] },
  { slug: 'stairway-accident-lawyer', title: 'Stairway Accident Lawyer', shortTitle: 'Stairway Accidents', description: 'Stairway fall injury claims.', heroImage: 'stairway.jpg', category: 'Workplace & Premises', injuries: ['Traumatic Brain Injuries', 'Spinal Cord Injuries', 'Broken Bones', 'Hip Fractures', 'Wrist Fractures', 'Ankle Injuries', 'Back Injuries', 'Facial Injuries'] },
  { slug: 'uneven-surface-accident-lawyer', title: 'Uneven Surface Accident Lawyer', shortTitle: 'Uneven Surface Accidents', description: 'Trip and fall on uneven surfaces.', heroImage: 'uneven-surface.jpg', category: 'Workplace & Premises', injuries: ['Ankle Sprains & Fractures', 'Knee Injuries', 'Hip Fractures', 'Wrist Fractures', 'Back Injuries', 'Shoulder Injuries', 'Facial Injuries', 'Traumatic Brain Injuries'] },
  { slug: 'poor-lighting-accident-lawyer', title: 'Poor Lighting Accident Lawyer', shortTitle: 'Poor Lighting Accidents', description: 'Inadequate lighting injury claims.', heroImage: 'poor-lighting.jpg', category: 'Workplace & Premises', injuries: ['Trip & Fall Injuries', 'Slip & Fall Injuries', 'Assault Injuries', 'Traumatic Brain Injuries', 'Broken Bones', 'Soft Tissue Injuries', 'Back Injuries', 'Hip Fractures'] },
  { slug: 'cluttered-aisle-accident-lawyer', title: 'Cluttered Aisle Accident Lawyer', shortTitle: 'Cluttered Aisle Accidents', description: 'Store aisle hazard claims.', heroImage: 'cluttered-aisle.jpg', category: 'Workplace & Premises', injuries: ['Trip & Fall Injuries', 'Broken Bones', 'Back Injuries', 'Knee Injuries', 'Ankle Injuries', 'Wrist Fractures', 'Soft Tissue Injuries', 'Traumatic Brain Injuries'] },
  { slug: 'weather-related-fall-lawyer', title: 'Weather-Related Fall Lawyer', shortTitle: 'Weather-Related Falls', description: 'Ice, snow, and weather hazard claims.', heroImage: 'weather-related.jpg', category: 'Workplace & Premises', injuries: ['Hip Fractures', 'Wrist Fractures', 'Back Injuries', 'Traumatic Brain Injuries', 'Tailbone Injuries', 'Ankle Injuries', 'Knee Injuries', 'Soft Tissue Injuries'] },
  { slug: 'medical-malpractice-lawyer', title: 'Medical Malpractice Lawyer', shortTitle: 'Medical Malpractice', description: 'Doctor and hospital negligence claims.', heroImage: 'medical-malpractice.jpg', category: 'Workplace & Premises', injuries: ['Surgical Errors', 'Misdiagnosis', 'Medication Errors', 'Birth Injuries', 'Anesthesia Errors', 'Hospital Infections', 'Delayed Treatment', 'Wrongful Death'] },
  { slug: 'product-liability-lawyer', title: 'Product Liability Lawyer', shortTitle: 'Product Liability', description: 'Defective product injury claims.', heroImage: 'product-liability.jpg', category: 'Workplace & Premises', injuries: ['Burns', 'Lacerations', 'Choking Hazards', 'Poisoning', 'Electrical Injuries', 'Traumatic Brain Injuries', 'Broken Bones', 'Wrongful Death'] },

  // Civil Rights
  { slug: 'police-brutality-lawyer', title: 'Police Brutality Lawyer', shortTitle: 'Police Brutality', description: 'Police misconduct and brutality claims.', heroImage: 'police-brutality.jpg', category: 'Civil Rights', injuries: ['Traumatic Brain Injuries', 'Broken Bones', 'Internal Injuries', 'Taser Injuries', 'Asphyxiation Injuries', 'Gunshot Wounds', 'Psychological Trauma (PTSD)', 'Wrongful Death'] },
  { slug: 'excessive-force-lawyer', title: 'Excessive Force Lawyer', shortTitle: 'Excessive Force', description: 'Law enforcement excessive force claims.', heroImage: 'excessive-force.jpg', category: 'Civil Rights', injuries: ['Traumatic Brain Injuries', 'Broken Bones', 'Internal Bleeding', 'Taser Burns & Cardiac Issues', 'Baton Injuries', 'Pepper Spray Injuries', 'Psychological Trauma', 'Wrongful Death'] },
  { slug: 'wrongful-arrest-lawyer', title: 'Wrongful Arrest Lawyer', shortTitle: 'Wrongful Arrest', description: 'False arrest and wrongful detention claims.', heroImage: 'wrongful-arrest.jpg', category: 'Civil Rights', injuries: ['Physical Assault Injuries', 'Handcuff Injuries', 'Psychological Trauma', 'Lost Employment', 'Reputation Damage', 'PTSD', 'Anxiety & Depression', 'Physical Restraint Injuries'] },
  { slug: 'false-imprisonment-lawyer', title: 'False Imprisonment Lawyer', shortTitle: 'False Imprisonment', description: 'Unlawful detention and imprisonment claims.', heroImage: 'false-imprisonment.jpg', category: 'Civil Rights', injuries: ['Physical Assault', 'Sexual Assault', 'Psychological Trauma', 'Medical Neglect Injuries', 'Malnutrition', 'PTSD', 'Anxiety & Depression', 'Lost Wages & Opportunities'] },
  { slug: 'malicious-prosecution-lawyer', title: 'Malicious Prosecution Lawyer', shortTitle: 'Malicious Prosecution', description: 'Wrongful prosecution civil claims.', heroImage: 'malicious-prosecution.jpg', category: 'Civil Rights', injuries: ['Psychological Trauma', 'PTSD', 'Anxiety & Depression', 'Lost Employment', 'Reputation Damage', 'Financial Losses', 'Family Separation', 'Physical Injuries During Arrest'] },
  { slug: 'illegal-search-seizure-lawyer', title: 'Illegal Search & Seizure Lawyer', shortTitle: 'Illegal Search & Seizure', description: 'Fourth Amendment violation claims.', heroImage: 'illegal-search.jpg', category: 'Civil Rights', injuries: ['Physical Assault Injuries', 'Property Damage', 'Psychological Trauma', 'Privacy Violations', 'PTSD', 'Financial Losses', 'Reputation Damage', 'Wrongful Arrest Injuries'] },
  { slug: 'police-shooting-lawyer', title: 'Police Shooting Lawyer', shortTitle: 'Police Shootings', description: 'Officer-involved shooting claims.', heroImage: 'police-shooting.jpg', category: 'Civil Rights', injuries: ['Gunshot Wounds', 'Traumatic Brain Injuries', 'Spinal Cord Injuries', 'Internal Organ Damage', 'Amputation', 'Permanent Disability', 'Psychological Trauma', 'Wrongful Death'] },
  { slug: 'jail-prison-abuse-lawyer', title: 'Jail/Prison Abuse Lawyer', shortTitle: 'Jail/Prison Abuse', description: 'Inmate abuse and neglect claims.', heroImage: 'jail-abuse.jpg', category: 'Civil Rights', injuries: ['Physical Assault Injuries', 'Sexual Assault', 'Medical Neglect', 'Malnutrition', 'Psychological Trauma', 'Excessive Force Injuries', 'Wrongful Death', 'Chronic Health Conditions'] },
  { slug: 'racial-profiling-lawyer', title: 'Racial Profiling Lawyer', shortTitle: 'Racial Profiling', description: 'Discriminatory policing claims.', heroImage: 'racial-profiling.jpg', category: 'Civil Rights', injuries: ['Physical Assault', 'Psychological Trauma', 'PTSD', 'Anxiety & Depression', 'Lost Employment', 'Reputation Damage', 'Wrongful Arrest Injuries', 'Emotional Distress'] },
  { slug: 'first-amendment-retaliation-lawyer', title: 'First Amendment Retaliation Lawyer', shortTitle: 'First Amendment Retaliation', description: 'Free speech retaliation claims.', heroImage: 'first-amendment.jpg', category: 'Civil Rights', injuries: ['Physical Assault', 'Wrongful Arrest Injuries', 'Psychological Trauma', 'Lost Employment', 'Reputation Damage', 'PTSD', 'Financial Losses', 'Emotional Distress'] },
]

export function getPracticeAreaBySlug(slug: string): PracticeArea | undefined {
  return practiceAreas.find(area => area.slug === slug)
}

export function getPracticeAreasByCategory(category: string): PracticeArea[] {
  return practiceAreas.filter(area => area.category === category)
}

export const categories = Array.from(new Set(practiceAreas.map(area => area.category)))
